/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of ElevatorInsurancePolicyExtendView
 *
 * @constructor
 */
angular.module('EasyBimehLandingLib')
    .factory('ElevatorInsurancePolicyExtendView', ['BaseModel', ElevatorInsurancePolicyExtendViewModel]);

    function ElevatorInsurancePolicyExtendViewModel(BaseModel) {
        var ElevatorInsurancePolicyExtendView = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.buildingUseTypeParamId = this.getValue(obj.buildingUseTypeParamId);
            this.elevatorTypeParamId = this.getValue(obj.elevatorTypeParamId);
            this.floors = this.getValue(obj.floors);
            this.elevatorCapacity = this.getValue(obj.elevatorCapacity);
            this.elevatorCapacityCargo = this.getValue(obj.elevatorCapacityCargo);
            this.defectOrganCoverageId = this.getValue(obj.defectOrganCoverageId);
            this.deathCapitalCoverageId = this.getValue(obj.deathCapitalCoverageId);
            this.financialCoverageId = this.getValue(obj.financialCoverageId);
            this.medicalCostCoverageId = this.getValue(obj.medicalCostCoverageId);
            this.riskLevelDiscountRate = this.getValue(obj.riskLevelDiscountRate);
            this.insuranceRiskLevelId = this.getValue(obj.insuranceRiskLevelId);
            this.discountRate = this.getValue(obj.discountRate);
            this.cityId = this.getValue(obj.cityId);
            this.provinceId = this.getValue(obj.provinceId);
            this.zipCode = this.getValue(obj.zipCode);
            this.addressPlaceBuilding = this.getValue(obj.addressPlaceBuilding);
            this.ownerCoverage = this.getValue(obj.ownerCoverage);
            this.riskLevelDiscount = this.getValue(obj.riskLevelDiscount);
            this.basePremium = this.getValue(obj.basePremium);
            this.allPremium = this.getValue(obj.allPremium);
            this.insuranceCompanyDiscountRate = this.getValue(obj.insuranceCompanyDiscountRate);
            this.insuranceCompanyDiscount = this.getValue(obj.insuranceCompanyDiscount);
            this.insuranceCentreDiscount = this.getValue(obj.insuranceCentreDiscount);
            this.coupenDiscount = this.getValue(obj.coupenDiscount);
            this.allDiscount = this.getValue(obj.allDiscount);
            this.exchangePremium = this.getValue(obj.exchangePremium);
        };

        ElevatorInsurancePolicyExtendView.prototype = new BaseModel();
        ElevatorInsurancePolicyExtendView.prototype.constructor = ElevatorInsurancePolicyExtendView;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        ElevatorInsurancePolicyExtendView.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'buildingUseTypeParamId', realName: 'buildingUseTypeParamId' },
                { name: 'elevatorTypeParamId', realName: 'elevatorTypeParamId' },
                { name: 'floors', realName: 'floors' },
                { name: 'elevatorCapacity', realName: 'elevatorCapacity' },
                { name: 'elevatorCapacityCargo', realName: 'elevatorCapacityCargo' },
                { name: 'defectOrganCoverageId', realName: 'defectOrganCoverageId' },
                { name: 'deathCapitalCoverageId', realName: 'deathCapitalCoverageId' },
                { name: 'financialCoverageId', realName: 'financialCoverageId' },
                { name: 'medicalCostCoverageId', realName: 'medicalCostCoverageId' },
                { name: 'riskLevelDiscountRate', realName: 'riskLevelDiscountRate' },
                { name: 'insuranceRiskLevelId', realName: 'insuranceRiskLevelId' },
                { name: 'discountRate', realName: 'discountRate' },
                { name: 'cityId', realName: 'cityId' },
                { name: 'provinceId', realName: 'provinceId' },
                { name: 'zipCode', realName: 'zipCode' },
                { name: 'addressPlaceBuilding', realName: 'addressPlaceBuilding' },
                { name: 'ownerCoverage', realName: 'ownerCoverage' },
                { name: 'riskLevelDiscount', realName: 'riskLevelDiscount' },
                { name: 'basePremium', realName: 'basePremium' },
                { name: 'allPremium', realName: 'allPremium' },
                { name: 'insuranceCompanyDiscountRate', realName: 'insuranceCompanyDiscountRate' },
                { name: 'insuranceCompanyDiscount', realName: 'insuranceCompanyDiscount' },
                { name: 'insuranceCentreDiscount', realName: 'insuranceCentreDiscount' },
                { name: 'coupenDiscount', realName: 'coupenDiscount' },
                { name: 'allDiscount', realName: 'allDiscount' },
                { name: 'exchangePremium', realName: 'exchangePremium' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        ElevatorInsurancePolicyExtendView.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getBuildingUseTypeParamId = function () {
            return this.buildingUseTypeParamId;
        };
    
        /**
         * Setter for BuildingUseTypeParamId
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setBuildingUseTypeParamId = function (value) {
            this.buildingUseTypeParamId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getElevatorTypeParamId = function () {
            return this.elevatorTypeParamId;
        };
    
        /**
         * Setter for ElevatorTypeParamId
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setElevatorTypeParamId = function (value) {
            this.elevatorTypeParamId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getFloors = function () {
            return this.floors;
        };
    
        /**
         * Setter for Floors
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setFloors = function (value) {
            this.floors = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getElevatorCapacity = function () {
            return this.elevatorCapacity;
        };
    
        /**
         * Setter for ElevatorCapacity
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setElevatorCapacity = function (value) {
            this.elevatorCapacity = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getElevatorCapacityCargo = function () {
            return this.elevatorCapacityCargo;
        };
    
        /**
         * Setter for ElevatorCapacityCargo
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setElevatorCapacityCargo = function (value) {
            this.elevatorCapacityCargo = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getDefectOrganCoverageId = function () {
            return this.defectOrganCoverageId;
        };
    
        /**
         * Setter for DefectOrganCoverageId
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setDefectOrganCoverageId = function (value) {
            this.defectOrganCoverageId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getDeathCapitalCoverageId = function () {
            return this.deathCapitalCoverageId;
        };
    
        /**
         * Setter for DeathCapitalCoverageId
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setDeathCapitalCoverageId = function (value) {
            this.deathCapitalCoverageId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getFinancialCoverageId = function () {
            return this.financialCoverageId;
        };
    
        /**
         * Setter for FinancialCoverageId
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setFinancialCoverageId = function (value) {
            this.financialCoverageId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getMedicalCostCoverageId = function () {
            return this.medicalCostCoverageId;
        };
    
        /**
         * Setter for MedicalCostCoverageId
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setMedicalCostCoverageId = function (value) {
            this.medicalCostCoverageId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getRiskLevelDiscountRate = function () {
            return this.riskLevelDiscountRate;
        };
    
        /**
         * Setter for RiskLevelDiscountRate
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setRiskLevelDiscountRate = function (value) {
            this.riskLevelDiscountRate = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getInsuranceRiskLevelId = function () {
            return this.insuranceRiskLevelId;
        };
    
        /**
         * Setter for InsuranceRiskLevelId
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setInsuranceRiskLevelId = function (value) {
            this.insuranceRiskLevelId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getDiscountRate = function () {
            return this.discountRate;
        };
    
        /**
         * Setter for DiscountRate
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setDiscountRate = function (value) {
            this.discountRate = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getCityId = function () {
            return this.cityId;
        };
    
        /**
         * Setter for CityId
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setCityId = function (value) {
            this.cityId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getProvinceId = function () {
            return this.provinceId;
        };
    
        /**
         * Setter for ProvinceId
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setProvinceId = function (value) {
            this.provinceId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getZipCode = function () {
            return this.zipCode;
        };
    
        /**
         * Setter for ZipCode
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setZipCode = function (value) {
            this.zipCode = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getAddressPlaceBuilding = function () {
            return this.addressPlaceBuilding;
        };
    
        /**
         * Setter for AddressPlaceBuilding
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setAddressPlaceBuilding = function (value) {
            this.addressPlaceBuilding = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {bool}
         */
        ElevatorInsurancePolicyExtendView.prototype.getOwnerCoverage = function () {
            return this.ownerCoverage;
        };
    
        /**
         * Setter for OwnerCoverage
         * 
         * @param {bool} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setOwnerCoverage = function (value) {
            this.ownerCoverage = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int}
         */
        ElevatorInsurancePolicyExtendView.prototype.getRiskLevelDiscount = function () {
            return this.riskLevelDiscount;
        };
    
        /**
         * Setter for RiskLevelDiscount
         * 
         * @param {int} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setRiskLevelDiscount = function (value) {
            this.riskLevelDiscount = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getBasePremium = function () {
            return this.basePremium;
        };
    
        /**
         * Setter for BasePremium
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setBasePremium = function (value) {
            this.basePremium = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ElevatorInsurancePolicyExtendView.prototype.getAllPremium = function () {
            return this.allPremium;
        };
    
        /**
         * Setter for AllPremium
         * 
         * @param {string|null} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setAllPremium = function (value) {
            this.allPremium = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int}
         */
        ElevatorInsurancePolicyExtendView.prototype.getInsuranceCompanyDiscountRate = function () {
            return this.insuranceCompanyDiscountRate;
        };
    
        /**
         * Setter for InsuranceCompanyDiscountRate
         * 
         * @param {int} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setInsuranceCompanyDiscountRate = function (value) {
            this.insuranceCompanyDiscountRate = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int}
         */
        ElevatorInsurancePolicyExtendView.prototype.getInsuranceCompanyDiscount = function () {
            return this.insuranceCompanyDiscount;
        };
    
        /**
         * Setter for InsuranceCompanyDiscount
         * 
         * @param {int} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setInsuranceCompanyDiscount = function (value) {
            this.insuranceCompanyDiscount = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int}
         */
        ElevatorInsurancePolicyExtendView.prototype.getInsuranceCentreDiscount = function () {
            return this.insuranceCentreDiscount;
        };
    
        /**
         * Setter for InsuranceCentreDiscount
         * 
         * @param {int} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setInsuranceCentreDiscount = function (value) {
            this.insuranceCentreDiscount = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int}
         */
        ElevatorInsurancePolicyExtendView.prototype.getCoupenDiscount = function () {
            return this.coupenDiscount;
        };
    
        /**
         * Setter for CoupenDiscount
         * 
         * @param {int} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setCoupenDiscount = function (value) {
            this.coupenDiscount = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int}
         */
        ElevatorInsurancePolicyExtendView.prototype.getAllDiscount = function () {
            return this.allDiscount;
        };
    
        /**
         * Setter for AllDiscount
         * 
         * @param {int} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setAllDiscount = function (value) {
            this.allDiscount = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int}
         */
        ElevatorInsurancePolicyExtendView.prototype.getExchangePremium = function () {
            return this.exchangePremium;
        };
    
        /**
         * Setter for ExchangePremium
         * 
         * @param {int} value 
         */
        ElevatorInsurancePolicyExtendView.prototype.setExchangePremium = function (value) {
            this.exchangePremium = value;
        };
    
        return ElevatorInsurancePolicyExtendView;
    }

}(angular));
