/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of ExtraDataBaseModelInsuranceCentrePolicyTypes
 *
 * @constructor
 */
angular.module('EasyBimehLandingLib')
    .factory('ExtraDataBaseModelInsuranceCentrePolicyTypes',
        ['BaseModel',         ExtraDataBaseModelInsuranceCentrePolicyTypesModel
    ]);

    function ExtraDataBaseModelInsuranceCentrePolicyTypesModel(BaseModel) {
        var ExtraDataBaseModelInsuranceCentrePolicyTypes = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.insuranceTypesCount = this.getValue(obj.insuranceTypesCount);
            this.hasPlan = this.getValue(obj.hasPlan);
        };

        ExtraDataBaseModelInsuranceCentrePolicyTypes.prototype = new BaseModel();
        ExtraDataBaseModelInsuranceCentrePolicyTypes.prototype.constructor = ExtraDataBaseModelInsuranceCentrePolicyTypes;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        ExtraDataBaseModelInsuranceCentrePolicyTypes.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'insuranceTypesCount', realName: 'insuranceTypesCount' },
                { name: 'hasPlan', realName: 'hasPlan' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        ExtraDataBaseModelInsuranceCentrePolicyTypes.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int}
         */
        ExtraDataBaseModelInsuranceCentrePolicyTypes.prototype.getInsuranceTypesCount = function () {
            return this.insuranceTypesCount;
        };
    
        /**
         * Setter for InsuranceTypesCount
         * 
         * @param {int} value 
         */
        ExtraDataBaseModelInsuranceCentrePolicyTypes.prototype.setInsuranceTypesCount = function (value) {
            this.insuranceTypesCount = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {bool}
         */
        ExtraDataBaseModelInsuranceCentrePolicyTypes.prototype.getHasPlan = function () {
            return this.hasPlan;
        };
    
        /**
         * Setter for HasPlan
         * 
         * @param {bool} value 
         */
        ExtraDataBaseModelInsuranceCentrePolicyTypes.prototype.setHasPlan = function (value) {
            this.hasPlan = value;
        };
    
        return ExtraDataBaseModelInsuranceCentrePolicyTypes;
    }

}(angular));
