/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of ExtraDataBaseModelPortalLandingPage
 *
 * @constructor
 */
angular.module('EasyBimehLandingLib')
    .factory('ExtraDataBaseModelPortalLandingPage', ['BaseModel', ExtraDataBaseModelPortalLandingPageModel]);

    function ExtraDataBaseModelPortalLandingPageModel(BaseModel) {
        var ExtraDataBaseModelPortalLandingPage = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.hasPlan = this.getValue(obj.hasPlan);
        };

        ExtraDataBaseModelPortalLandingPage.prototype = new BaseModel();
        ExtraDataBaseModelPortalLandingPage.prototype.constructor = ExtraDataBaseModelPortalLandingPage;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        ExtraDataBaseModelPortalLandingPage.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'hasPlan', realName: 'hasPlan' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        ExtraDataBaseModelPortalLandingPage.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {bool}
         */
        ExtraDataBaseModelPortalLandingPage.prototype.getHasPlan = function () {
            return this.hasPlan;
        };
    
        /**
         * Setter for HasPlan
         * 
         * @param {bool} value 
         */
        ExtraDataBaseModelPortalLandingPage.prototype.setHasPlan = function (value) {
            this.hasPlan = value;
        };
    
        return ExtraDataBaseModelPortalLandingPage;
    }

}(angular));
