/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of InsuranceData
 *
 * @constructor
 */
angular.module('EasyBimehLandingLib')
    .factory('InsuranceData', ['BaseModel', InsuranceDataModel]);

    function InsuranceDataModel(BaseModel) {
        var InsuranceData = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.electronicEquipmentInsurancePolicyExtendView =
          this.getValue(obj.electronicEquipmentInsurancePolicyExtendView);
            this.electronicEquipmentInsurancePolicyFilter = this.getValue(obj.electronicEquipmentInsurancePolicyFilter);
            this.id = this.getValue(obj.id);
            this.selectedInsurancePolicyHasBeenChanged = this.getValue(obj.selectedInsurancePolicyHasBeenChanged);
            this.isPaymented = this.getValue(obj.isPaymented);
            this.payable = this.getValue(obj.payable);
            this.paymented = this.getValue(obj.paymented);
            this.conflict = this.getValue(obj.conflict);
            this.hasConflictDocument = this.getValue(obj.hasConflictDocument);
            this.initialPrice = this.getValue(obj.initialPrice);
            this.finalPrice = this.getValue(obj.finalPrice);
            this.insuranceCompanyName = this.getValue(obj.insuranceCompanyName);
            this.insuranceCentreName = this.getValue(obj.insuranceCentreName);
            this.isInsuranceCentreAdmin = this.getValue(obj.isInsuranceCentreAdmin);
            this.insurancePolicyPaymentDocuments = this.getValue(obj.insurancePolicyPaymentDocuments);
            this.insurancePolicyConflict = this.getValue(obj.insurancePolicyConflict);
            this.insurancePolicyCondition = this.getValue(obj.insurancePolicyCondition);
            this.person = this.getValue(obj.person);
            this.insurancePolicy = this.getValue(obj.insurancePolicy);
            this.shoppingCard = this.getValue(obj.shoppingCard);
            this.shoppingCardPostalPacket = this.getValue(obj.shoppingCardPostalPacket);
        };

        InsuranceData.prototype = new BaseModel();
        InsuranceData.prototype.constructor = InsuranceData;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        InsuranceData.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                {
                    name: 'electronicEquipmentInsurancePolicyExtendView',
                    realName: 'electronicEquipmentInsurancePolicyExtendView',
                    type: 'ElectronicEquipmentInsurancePolicyExtendView',
                },
                {
                    name: 'electronicEquipmentInsurancePolicyFilter',
                    realName: 'electronicEquipmentInsurancePolicyFilter',
                    type: 'ElectronicEquipmentInsurancePolicyFilter',
                },
                { name: 'id', realName: 'id' },
                { name: 'selectedInsurancePolicyHasBeenChanged', realName: 'selectedInsurancePolicyHasBeenChanged' },
                { name: 'isPaymented', realName: 'isPaymented' },
                { name: 'payable', realName: 'payable' },
                { name: 'paymented', realName: 'paymented' },
                { name: 'conflict', realName: 'conflict' },
                { name: 'hasConflictDocument', realName: 'hasConflictDocument' },
                { name: 'initialPrice', realName: 'initialPrice' },
                { name: 'finalPrice', realName: 'finalPrice' },
                { name: 'insuranceCompanyName', realName: 'insuranceCompanyName' },
                { name: 'insuranceCentreName', realName: 'insuranceCentreName' },
                { name: 'isInsuranceCentreAdmin', realName: 'isInsuranceCentreAdmin' },
                { name: 'insurancePolicyPaymentDocuments', realName: 'insurancePolicyPaymentDocuments', array: true },
                { name: 'insurancePolicyConflict', realName: 'insurancePolicyConflict' },
                { name: 'insurancePolicyCondition', realName: 'insurancePolicyCondition' },
                { name: 'person', realName: 'person' },
                { name: 'insurancePolicy', realName: 'insurancePolicy' },
                { name: 'shoppingCard', realName: 'shoppingCard' },
                { name: 'shoppingCardPostalPacket', realName: 'shoppingCardPostalPacket' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        InsuranceData.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {ElectronicEquipmentInsurancePolicyExtendView}
         */
        InsuranceData.prototype.getElectronicEquipmentInsurancePolicyExtendView = function () {
            return this.electronicEquipmentInsurancePolicyExtendView;
        };
    
        /**
         * Setter for ElectronicEquipmentInsurancePolicyExtendView
         * 
         * @param {ElectronicEquipmentInsurancePolicyExtendView} value 
         */
        InsuranceData.prototype.setElectronicEquipmentInsurancePolicyExtendView = function (value) {
            this.electronicEquipmentInsurancePolicyExtendView = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {ElectronicEquipmentInsurancePolicyFilter}
         */
        InsuranceData.prototype.getElectronicEquipmentInsurancePolicyFilter = function () {
            return this.electronicEquipmentInsurancePolicyFilter;
        };
    
        /**
         * Setter for ElectronicEquipmentInsurancePolicyFilter
         * 
         * @param {ElectronicEquipmentInsurancePolicyFilter} value 
         */
        InsuranceData.prototype.setElectronicEquipmentInsurancePolicyFilter = function (value) {
            this.electronicEquipmentInsurancePolicyFilter = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int}
         */
        InsuranceData.prototype.getId = function () {
            return this.id;
        };
    
        /**
         * Setter for Id
         * 
         * @param {int} value 
         */
        InsuranceData.prototype.setId = function (value) {
            this.id = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {bool}
         */
        InsuranceData.prototype.getSelectedInsurancePolicyHasBeenChanged = function () {
            return this.selectedInsurancePolicyHasBeenChanged;
        };
    
        /**
         * Setter for SelectedInsurancePolicyHasBeenChanged
         * 
         * @param {bool} value 
         */
        InsuranceData.prototype.setSelectedInsurancePolicyHasBeenChanged = function (value) {
            this.selectedInsurancePolicyHasBeenChanged = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {bool}
         */
        InsuranceData.prototype.getIsPaymented = function () {
            return this.isPaymented;
        };
    
        /**
         * Setter for IsPaymented
         * 
         * @param {bool} value 
         */
        InsuranceData.prototype.setIsPaymented = function (value) {
            this.isPaymented = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        InsuranceData.prototype.getPayable = function () {
            return this.payable;
        };
    
        /**
         * Setter for Payable
         * 
         * @param {string|null} value 
         */
        InsuranceData.prototype.setPayable = function (value) {
            this.payable = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        InsuranceData.prototype.getPaymented = function () {
            return this.paymented;
        };
    
        /**
         * Setter for Paymented
         * 
         * @param {string|null} value 
         */
        InsuranceData.prototype.setPaymented = function (value) {
            this.paymented = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        InsuranceData.prototype.getConflict = function () {
            return this.conflict;
        };
    
        /**
         * Setter for Conflict
         * 
         * @param {string|null} value 
         */
        InsuranceData.prototype.setConflict = function (value) {
            this.conflict = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {bool}
         */
        InsuranceData.prototype.getHasConflictDocument = function () {
            return this.hasConflictDocument;
        };
    
        /**
         * Setter for HasConflictDocument
         * 
         * @param {bool} value 
         */
        InsuranceData.prototype.setHasConflictDocument = function (value) {
            this.hasConflictDocument = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        InsuranceData.prototype.getInitialPrice = function () {
            return this.initialPrice;
        };
    
        /**
         * Setter for InitialPrice
         * 
         * @param {string|null} value 
         */
        InsuranceData.prototype.setInitialPrice = function (value) {
            this.initialPrice = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        InsuranceData.prototype.getFinalPrice = function () {
            return this.finalPrice;
        };
    
        /**
         * Setter for FinalPrice
         * 
         * @param {string|null} value 
         */
        InsuranceData.prototype.setFinalPrice = function (value) {
            this.finalPrice = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        InsuranceData.prototype.getInsuranceCompanyName = function () {
            return this.insuranceCompanyName;
        };
    
        /**
         * Setter for InsuranceCompanyName
         * 
         * @param {string|null} value 
         */
        InsuranceData.prototype.setInsuranceCompanyName = function (value) {
            this.insuranceCompanyName = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        InsuranceData.prototype.getInsuranceCentreName = function () {
            return this.insuranceCentreName;
        };
    
        /**
         * Setter for InsuranceCentreName
         * 
         * @param {string|null} value 
         */
        InsuranceData.prototype.setInsuranceCentreName = function (value) {
            this.insuranceCentreName = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {bool}
         */
        InsuranceData.prototype.getIsInsuranceCentreAdmin = function () {
            return this.isInsuranceCentreAdmin;
        };
    
        /**
         * Setter for IsInsuranceCentreAdmin
         * 
         * @param {bool} value 
         */
        InsuranceData.prototype.setIsInsuranceCentreAdmin = function (value) {
            this.isInsuranceCentreAdmin = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array}
         */
        InsuranceData.prototype.getInsurancePolicyPaymentDocuments = function () {
            return this.insurancePolicyPaymentDocuments;
        };
    
        /**
         * Setter for InsurancePolicyPaymentDocuments
         * 
         * @param {array} value 
         */
        InsuranceData.prototype.setInsurancePolicyPaymentDocuments = function (value) {
            this.insurancePolicyPaymentDocuments = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        InsuranceData.prototype.getInsurancePolicyConflict = function () {
            return this.insurancePolicyConflict;
        };
    
        /**
         * Setter for InsurancePolicyConflict
         * 
         * @param {string|null} value 
         */
        InsuranceData.prototype.setInsurancePolicyConflict = function (value) {
            this.insurancePolicyConflict = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        InsuranceData.prototype.getInsurancePolicyCondition = function () {
            return this.insurancePolicyCondition;
        };
    
        /**
         * Setter for InsurancePolicyCondition
         * 
         * @param {string|null} value 
         */
        InsuranceData.prototype.setInsurancePolicyCondition = function (value) {
            this.insurancePolicyCondition = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        InsuranceData.prototype.getPerson = function () {
            return this.person;
        };
    
        /**
         * Setter for Person
         * 
         * @param {string|null} value 
         */
        InsuranceData.prototype.setPerson = function (value) {
            this.person = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        InsuranceData.prototype.getInsurancePolicy = function () {
            return this.insurancePolicy;
        };
    
        /**
         * Setter for InsurancePolicy
         * 
         * @param {string|null} value 
         */
        InsuranceData.prototype.setInsurancePolicy = function (value) {
            this.insurancePolicy = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        InsuranceData.prototype.getShoppingCard = function () {
            return this.shoppingCard;
        };
    
        /**
         * Setter for ShoppingCard
         * 
         * @param {string|null} value 
         */
        InsuranceData.prototype.setShoppingCard = function (value) {
            this.shoppingCard = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        InsuranceData.prototype.getShoppingCardPostalPacket = function () {
            return this.shoppingCardPostalPacket;
        };
    
        /**
         * Setter for ShoppingCardPostalPacket
         * 
         * @param {string|null} value 
         */
        InsuranceData.prototype.setShoppingCardPostalPacket = function (value) {
            this.shoppingCardPostalPacket = value;
        };
    
        return InsuranceData;
    }

}(angular));
