/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of InsuranceExtraCoverageExtraData
 *
 * @constructor
 */
angular.module('EasyBimehLandingLib')
    .factory('InsuranceExtraCoverageExtraData', ['BaseModel', InsuranceExtraCoverageExtraDataModel]);

    function InsuranceExtraCoverageExtraDataModel(BaseModel) {
        var InsuranceExtraCoverageExtraData = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.defaultStatus = this.getValue(obj.defaultStatus);
            this.requiringExpertVisit = this.getValue(obj.requiringExpertVisit);
        };

        InsuranceExtraCoverageExtraData.prototype = new BaseModel();
        InsuranceExtraCoverageExtraData.prototype.constructor = InsuranceExtraCoverageExtraData;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        InsuranceExtraCoverageExtraData.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'defaultStatus', realName: 'defaultStatus' },
                { name: 'requiringExpertVisit', realName: 'requiringExpertVisit' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        InsuranceExtraCoverageExtraData.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {bool}
         */
        InsuranceExtraCoverageExtraData.prototype.getDefaultStatus = function () {
            return this.defaultStatus;
        };
    
        /**
         * Setter for DefaultStatus
         * 
         * @param {bool} value 
         */
        InsuranceExtraCoverageExtraData.prototype.setDefaultStatus = function (value) {
            this.defaultStatus = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {bool}
         */
        InsuranceExtraCoverageExtraData.prototype.getRequiringExpertVisit = function () {
            return this.requiringExpertVisit;
        };
    
        /**
         * Setter for RequiringExpertVisit
         * 
         * @param {bool} value 
         */
        InsuranceExtraCoverageExtraData.prototype.setRequiringExpertVisit = function (value) {
            this.requiringExpertVisit = value;
        };
    
        return InsuranceExtraCoverageExtraData;
    }

}(angular));
