/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of LiabilityDoctorInsurancePolicyExtendView
 *
 * @constructor
 */
angular.module('EasyBimehLandingLib')
    .factory('LiabilityDoctorInsurancePolicyExtendView', ['BaseModel', LiabilityDoctorInsurancePolicyExtendViewModel]);

    function LiabilityDoctorInsurancePolicyExtendViewModel(BaseModel) {
        var LiabilityDoctorInsurancePolicyExtendView = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.liabilityDoctorCoverageRateId = this.getValue(obj.liabilityDoctorCoverageRateId);
            this.activityAreaParamId = this.getValue(obj.activityAreaParamId);
            this.expertiseParamId = this.getValue(obj.expertiseParamId);
            this.commitmentCeilingParamId = this.getValue(obj.commitmentCeilingParamId);
            this.insuranceRiskLevelId = this.getValue(obj.insuranceRiskLevelId);
            this.currentInsuranceDeadline = this.getValue(obj.currentInsuranceDeadline);
            this.riskLevelDiscountRate = this.getValue(obj.riskLevelDiscountRate);
            this.physicalCommitment = this.getValue(obj.physicalCommitment);
            this.discountRate = this.getValue(obj.discountRate);
            this.basePremium = this.getValue(obj.basePremium);
            this.allPremium = this.getValue(obj.allPremium);
            this.allExtraValues = this.getValue(obj.allExtraValues);
            this.insuranceCompanyDiscountRate = this.getValue(obj.insuranceCompanyDiscountRate);
            this.allDiscount = this.getValue(obj.allDiscount);
            this.exchangePremium = this.getValue(obj.exchangePremium);
            this.doctorName = this.getValue(obj.doctorName);
            this.medicalSystemNO = this.getValue(obj.medicalSystemNO);
            this.address = this.getValue(obj.address);
            this.isResident = this.getValue(obj.isResident);
            this.isStudent = this.getValue(obj.isStudent);
            this.hasClinic = this.getValue(obj.hasClinic);
            this.metaMediaMedicalSystemLicenseId = this.getValue(obj.metaMediaMedicalSystemLicenseId);
            this.metaMediaMedicalSystemLicenseUrl = this.getValue(obj.metaMediaMedicalSystemLicenseUrl);
            this.metaMediaNationalCardId = this.getValue(obj.metaMediaNationalCardId);
            this.metaMediaNationalCardUrl = this.getValue(obj.metaMediaNationalCardUrl);
            this.metaMediaCurrentInsurancePolicyId = this.getValue(obj.metaMediaCurrentInsurancePolicyId);
            this.metaMediaCurrentInsurancePolicyUrl = this.getValue(obj.metaMediaCurrentInsurancePolicyUrl);
            this.activityAreaEnumName = this.getValue(obj.activityAreaEnumName);
            this.activityAreaTitle = this.getValue(obj.activityAreaTitle);
            this.expertiseTitle = this.getValue(obj.expertiseTitle);
            this.docterStatusTitle = this.getValue(obj.docterStatusTitle);
        };

        LiabilityDoctorInsurancePolicyExtendView.prototype = new BaseModel();
        LiabilityDoctorInsurancePolicyExtendView.prototype.constructor = LiabilityDoctorInsurancePolicyExtendView;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'liabilityDoctorCoverageRateId', realName: 'liabilityDoctorCoverageRateId' },
                { name: 'activityAreaParamId', realName: 'activityAreaParamId' },
                { name: 'expertiseParamId', realName: 'expertiseParamId' },
                { name: 'commitmentCeilingParamId', realName: 'commitmentCeilingParamId' },
                { name: 'insuranceRiskLevelId', realName: 'insuranceRiskLevelId' },
                { name: 'currentInsuranceDeadline', realName: 'currentInsuranceDeadline' },
                { name: 'riskLevelDiscountRate', realName: 'riskLevelDiscountRate' },
                { name: 'physicalCommitment', realName: 'physicalCommitment' },
                { name: 'discountRate', realName: 'discountRate' },
                { name: 'basePremium', realName: 'basePremium' },
                { name: 'allPremium', realName: 'allPremium' },
                { name: 'allExtraValues', realName: 'allExtraValues' },
                { name: 'insuranceCompanyDiscountRate', realName: 'insuranceCompanyDiscountRate' },
                { name: 'allDiscount', realName: 'allDiscount' },
                { name: 'exchangePremium', realName: 'exchangePremium' },
                { name: 'doctorName', realName: 'doctorName' },
                { name: 'medicalSystemNO', realName: 'medicalSystemNO' },
                { name: 'address', realName: 'address' },
                { name: 'isResident', realName: 'isResident' },
                { name: 'isStudent', realName: 'isStudent' },
                { name: 'hasClinic', realName: 'hasClinic' },
                { name: 'metaMediaMedicalSystemLicenseId', realName: 'metaMediaMedicalSystemLicenseId' },
                { name: 'metaMediaMedicalSystemLicenseUrl', realName: 'metaMediaMedicalSystemLicenseUrl' },
                { name: 'metaMediaNationalCardId', realName: 'metaMediaNationalCardId' },
                { name: 'metaMediaNationalCardUrl', realName: 'metaMediaNationalCardUrl' },
                { name: 'metaMediaCurrentInsurancePolicyId', realName: 'metaMediaCurrentInsurancePolicyId' },
                { name: 'metaMediaCurrentInsurancePolicyUrl', realName: 'metaMediaCurrentInsurancePolicyUrl' },
                { name: 'activityAreaEnumName', realName: 'activityAreaEnumName' },
                { name: 'activityAreaTitle', realName: 'activityAreaTitle' },
                { name: 'expertiseTitle', realName: 'expertiseTitle' },
                { name: 'docterStatusTitle', realName: 'docterStatusTitle' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * شناسه ی نرخ پوشش پزشکی
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getLiabilityDoctorCoverageRateId = function () {
            return this.liabilityDoctorCoverageRateId;
        };
    
        /**
         * Setter for LiabilityDoctorCoverageRateId
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setLiabilityDoctorCoverageRateId = function (value) {
            this.liabilityDoctorCoverageRateId = value;
        };
    
        /**
         * شناسه ی دوره های فعالیت
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getActivityAreaParamId = function () {
            return this.activityAreaParamId;
        };
    
        /**
         * Setter for ActivityAreaParamId
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setActivityAreaParamId = function (value) {
            this.activityAreaParamId = value;
        };
    
        /**
         * شاسه ی تخصص
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getExpertiseParamId = function () {
            return this.expertiseParamId;
        };
    
        /**
         * Setter for ExpertiseParamId
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setExpertiseParamId = function (value) {
            this.expertiseParamId = value;
        };
    
        /**
         * شناسه ی سقف تعهد
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getCommitmentCeilingParamId = function () {
            return this.commitmentCeilingParamId;
        };
    
        /**
         * Setter for CommitmentCeilingParamId
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setCommitmentCeilingParamId = function (value) {
            this.commitmentCeilingParamId = value;
        };
    
        /**
         * شناسه ی تخفیف
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getInsuranceRiskLevelId = function () {
            return this.insuranceRiskLevelId;
        };
    
        /**
         * Setter for InsuranceRiskLevelId
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setInsuranceRiskLevelId = function (value) {
            this.insuranceRiskLevelId = value;
        };
    
        /**
         * تاریخ پایان بیمه نامه
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getCurrentInsuranceDeadline = function () {
            return this.currentInsuranceDeadline;
        };
    
        /**
         * Setter for CurrentInsuranceDeadline
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setCurrentInsuranceDeadline = function (value) {
            this.currentInsuranceDeadline = value;
        };
    
        /**
         * نرخ تخفیف پوشش
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getRiskLevelDiscountRate = function () {
            return this.riskLevelDiscountRate;
        };
    
        /**
         * Setter for RiskLevelDiscountRate
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setRiskLevelDiscountRate = function (value) {
            this.riskLevelDiscountRate = value;
        };
    
        /**
         * خسارت جانی
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getPhysicalCommitment = function () {
            return this.physicalCommitment;
        };
    
        /**
         * Setter for PhysicalCommitment
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setPhysicalCommitment = function (value) {
            this.physicalCommitment = value;
        };
    
        /**
         * نرخ تخفیف
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getDiscountRate = function () {
            return this.discountRate;
        };
    
        /**
         * Setter for DiscountRate
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setDiscountRate = function (value) {
            this.discountRate = value;
        };
    
        /**
         * پوشش پایه
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getBasePremium = function () {
            return this.basePremium;
        };
    
        /**
         * Setter for BasePremium
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setBasePremium = function (value) {
            this.basePremium = value;
        };
    
        /**
         * پوشش ها
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getAllPremium = function () {
            return this.allPremium;
        };
    
        /**
         * Setter for AllPremium
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setAllPremium = function (value) {
            this.allPremium = value;
        };
    
        /**
         * اطلاعات اضافه
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getAllExtraValues = function () {
            return this.allExtraValues;
        };
    
        /**
         * Setter for AllExtraValues
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setAllExtraValues = function (value) {
            this.allExtraValues = value;
        };
    
        /**
         * نرخ تخفیف شرکت بیمه
         *
         * @return {int}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getInsuranceCompanyDiscountRate = function () {
            return this.insuranceCompanyDiscountRate;
        };
    
        /**
         * Setter for InsuranceCompanyDiscountRate
         * 
         * @param {int} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setInsuranceCompanyDiscountRate = function (value) {
            this.insuranceCompanyDiscountRate = value;
        };
    
        /**
         * لیست تخفیفات
         *
         * @return {int}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getAllDiscount = function () {
            return this.allDiscount;
        };
    
        /**
         * Setter for AllDiscount
         * 
         * @param {int} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setAllDiscount = function (value) {
            this.allDiscount = value;
        };
    
        /**
         * نوع ارز حق بیمه
         *
         * @return {int}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getExchangePremium = function () {
            return this.exchangePremium;
        };
    
        /**
         * Setter for ExchangePremium
         * 
         * @param {int} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setExchangePremium = function (value) {
            this.exchangePremium = value;
        };
    
        /**
         * نام پزشک
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getDoctorName = function () {
            return this.doctorName;
        };
    
        /**
         * Setter for DoctorName
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setDoctorName = function (value) {
            this.doctorName = value;
        };
    
        /**
         * شماره ی نظام پزشکی
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getMedicalSystemNO = function () {
            return this.medicalSystemNO;
        };
    
        /**
         * Setter for MedicalSystemNO
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setMedicalSystemNO = function (value) {
            this.medicalSystemNO = value;
        };
    
        /**
         * آدرس
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getAddress = function () {
            return this.address;
        };
    
        /**
         * Setter for Address
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setAddress = function (value) {
            this.address = value;
        };
    
        /**
         * آیا رزیدنت است؟
         *
         * @return {bool}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getIsResident = function () {
            return this.isResident;
        };
    
        /**
         * Setter for IsResident
         * 
         * @param {bool} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setIsResident = function (value) {
            this.isResident = value;
        };
    
        /**
         * آیا دانشجو است؟
         *
         * @return {bool}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getIsStudent = function () {
            return this.isStudent;
        };
    
        /**
         * Setter for IsStudent
         * 
         * @param {bool} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setIsStudent = function (value) {
            this.isStudent = value;
        };
    
        /**
         * دارای مطب؟
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getHasClinic = function () {
            return this.hasClinic;
        };
    
        /**
         * Setter for HasClinic
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setHasClinic = function (value) {
            this.hasClinic = value;
        };
    
        /**
         * شناسه ی گواهی نظام پزشکی
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getMetaMediaMedicalSystemLicenseId = function () {
            return this.metaMediaMedicalSystemLicenseId;
        };
    
        /**
         * Setter for MetaMediaMedicalSystemLicenseId
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setMetaMediaMedicalSystemLicenseId = function (value) {
            this.metaMediaMedicalSystemLicenseId = value;
        };
    
        /**
         * آدرس گواهی نظام پزشکی
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getMetaMediaMedicalSystemLicenseUrl = function () {
            return this.metaMediaMedicalSystemLicenseUrl;
        };
    
        /**
         * Setter for MetaMediaMedicalSystemLicenseUrl
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setMetaMediaMedicalSystemLicenseUrl = function (value) {
            this.metaMediaMedicalSystemLicenseUrl = value;
        };
    
        /**
         * شناسه ی کارت ملی
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getMetaMediaNationalCardId = function () {
            return this.metaMediaNationalCardId;
        };
    
        /**
         * Setter for MetaMediaNationalCardId
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setMetaMediaNationalCardId = function (value) {
            this.metaMediaNationalCardId = value;
        };
    
        /**
         * آدرس کارت ملی
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getMetaMediaNationalCardUrl = function () {
            return this.metaMediaNationalCardUrl;
        };
    
        /**
         * Setter for MetaMediaNationalCardUrl
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setMetaMediaNationalCardUrl = function (value) {
            this.metaMediaNationalCardUrl = value;
        };
    
        /**
         * شناسه ی بیمه نامه ی کنونی
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getMetaMediaCurrentInsurancePolicyId = function () {
            return this.metaMediaCurrentInsurancePolicyId;
        };
    
        /**
         * Setter for MetaMediaCurrentInsurancePolicyId
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setMetaMediaCurrentInsurancePolicyId = function (value) {
            this.metaMediaCurrentInsurancePolicyId = value;
        };
    
        /**
         * آدرس بیمه نامه ی کنونی
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getMetaMediaCurrentInsurancePolicyUrl = function () {
            return this.metaMediaCurrentInsurancePolicyUrl;
        };
    
        /**
         * Setter for MetaMediaCurrentInsurancePolicyUrl
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setMetaMediaCurrentInsurancePolicyUrl = function (value) {
            this.metaMediaCurrentInsurancePolicyUrl = value;
        };
    
        /**
         * شناسه ی دوره های بیمه نامه
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getActivityAreaEnumName = function () {
            return this.activityAreaEnumName;
        };
    
        /**
         * Setter for ActivityAreaEnumName
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setActivityAreaEnumName = function (value) {
            this.activityAreaEnumName = value;
        };
    
        /**
         * نام دوره ی بیمه نامه
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getActivityAreaTitle = function () {
            return this.activityAreaTitle;
        };
    
        /**
         * Setter for ActivityAreaTitle
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setActivityAreaTitle = function (value) {
            this.activityAreaTitle = value;
        };
    
        /**
         * نام تخصص
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getExpertiseTitle = function () {
            return this.expertiseTitle;
        };
    
        /**
         * Setter for ExpertiseTitle
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setExpertiseTitle = function (value) {
            this.expertiseTitle = value;
        };
    
        /**
         * وضعیت پزشک
         *
         * @return {string|null}
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.getDocterStatusTitle = function () {
            return this.docterStatusTitle;
        };
    
        /**
         * Setter for DocterStatusTitle
         * 
         * @param {string|null} value 
         */
        LiabilityDoctorInsurancePolicyExtendView.prototype.setDocterStatusTitle = function (value) {
            this.docterStatusTitle = value;
        };
    
        return LiabilityDoctorInsurancePolicyExtendView;
    }

}(angular));
