/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of SummaryNotic
 *
 * @constructor
 */
angular.module('EasyBimehLandingLib')
    .factory('SummaryNotic', ['BaseModel', SummaryNoticModel]);

    function SummaryNoticModel(BaseModel) {
        var SummaryNotic = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.id = this.getValue(obj.id);
            this.insuranceCentreId = this.getValue(obj.insuranceCentreId);
            this.articleType = this.getValue(obj.articleType);
            this.title = this.getValue(obj.title);
            this.summary = this.getValue(obj.summary);
            this.articleGroup = this.getValue(obj.articleGroup);
            this.metaMediaFileId = this.getValue(obj.metaMediaFileId);
            this.metaMediaFileUrl = this.getValue(obj.metaMediaFileUrl);
            this.publishPersianDate = this.getValue(obj.publishPersianDate);
        };

        SummaryNotic.prototype = new BaseModel();
        SummaryNotic.prototype.constructor = SummaryNotic;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        SummaryNotic.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'id', realName: 'id' },
                { name: 'insuranceCentreId', realName: 'insuranceCentreId' },
                { name: 'articleType', realName: 'articleType' },
                { name: 'title', realName: 'title' },
                { name: 'summary', realName: 'summary' },
                { name: 'articleGroup', realName: 'articleGroup' },
                { name: 'metaMediaFileId', realName: 'metaMediaFileId' },
                { name: 'metaMediaFileUrl', realName: 'metaMediaFileUrl' },
                { name: 'publishPersianDate', realName: 'publishPersianDate' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        SummaryNotic.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int}
         */
        SummaryNotic.prototype.getId = function () {
            return this.id;
        };
    
        /**
         * Setter for Id
         * 
         * @param {int} value 
         */
        SummaryNotic.prototype.setId = function (value) {
            this.id = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int}
         */
        SummaryNotic.prototype.getInsuranceCentreId = function () {
            return this.insuranceCentreId;
        };
    
        /**
         * Setter for InsuranceCentreId
         * 
         * @param {int} value 
         */
        SummaryNotic.prototype.setInsuranceCentreId = function (value) {
            this.insuranceCentreId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int}
         */
        SummaryNotic.prototype.getArticleType = function () {
            return this.articleType;
        };
    
        /**
         * Setter for ArticleType
         * 
         * @param {int} value 
         */
        SummaryNotic.prototype.setArticleType = function (value) {
            this.articleType = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        SummaryNotic.prototype.getTitle = function () {
            return this.title;
        };
    
        /**
         * Setter for Title
         * 
         * @param {string} value 
         */
        SummaryNotic.prototype.setTitle = function (value) {
            this.title = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        SummaryNotic.prototype.getSummary = function () {
            return this.summary;
        };
    
        /**
         * Setter for Summary
         * 
         * @param {string} value 
         */
        SummaryNotic.prototype.setSummary = function (value) {
            this.summary = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        SummaryNotic.prototype.getArticleGroup = function () {
            return this.articleGroup;
        };
    
        /**
         * Setter for ArticleGroup
         * 
         * @param {string} value 
         */
        SummaryNotic.prototype.setArticleGroup = function (value) {
            this.articleGroup = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int}
         */
        SummaryNotic.prototype.getMetaMediaFileId = function () {
            return this.metaMediaFileId;
        };
    
        /**
         * Setter for MetaMediaFileId
         * 
         * @param {int} value 
         */
        SummaryNotic.prototype.setMetaMediaFileId = function (value) {
            this.metaMediaFileId = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        SummaryNotic.prototype.getMetaMediaFileUrl = function () {
            return this.metaMediaFileUrl;
        };
    
        /**
         * Setter for MetaMediaFileUrl
         * 
         * @param {string} value 
         */
        SummaryNotic.prototype.setMetaMediaFileUrl = function (value) {
            this.metaMediaFileUrl = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        SummaryNotic.prototype.getPublishPersianDate = function () {
            return this.publishPersianDate;
        };
    
        /**
         * Setter for PublishPersianDate
         * 
         * @param {string} value 
         */
        SummaryNotic.prototype.setPublishPersianDate = function (value) {
            this.publishPersianDate = value;
        };
    
        return SummaryNotic;
    }

}(angular));
