/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of TrackingDamageStatus
 *
 * @constructor
 */
angular.module('EasyBimehLandingLib')
    .factory('TrackingDamageStatus', ['BaseModel', TrackingDamageStatusModel]);

    function TrackingDamageStatusModel(BaseModel) {
        var TrackingDamageStatus = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.trackingDamageFile = this.getValue(obj.trackingDamageFile);
        };

        TrackingDamageStatus.prototype = new BaseModel();
        TrackingDamageStatus.prototype.constructor = TrackingDamageStatus;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        TrackingDamageStatus.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'trackingDamageFile', realName: 'trackingDamageFile', array: true, type: 'TrackingDamageFile' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        TrackingDamageStatus.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array}
         */
        TrackingDamageStatus.prototype.getTrackingDamageFile = function () {
            return this.trackingDamageFile;
        };
    
        /**
         * Setter for TrackingDamageFile
         * 
         * @param {array} value 
         */
        TrackingDamageStatus.prototype.setTrackingDamageFile = function (value) {
            this.trackingDamageFile = value;
        };
    
        return TrackingDamageStatus;
    }

}(angular));
