/**
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of TravelInsurancePolicyExtendView
 *
 * @constructor
 */
angular.module('EasyBimehLandingLib')
    .factory('TravelInsurancePolicyExtendView', ['BaseModel', TravelInsurancePolicyExtendViewModel]);

    function TravelInsurancePolicyExtendViewModel(BaseModel) {
        var TravelInsurancePolicyExtendView = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.travelInsurancePolicyExtend = this.getValue(obj.travelInsurancePolicyExtend);
            this.travelInsurancePolicyExtendAges = this.getValue(obj.travelInsurancePolicyExtendAges);
            this.travelInsurancePolicyExtendPassengers = this.getValue(obj.travelInsurancePolicyExtendPassengers);
        };

        TravelInsurancePolicyExtendView.prototype = new BaseModel();
        TravelInsurancePolicyExtendView.prototype.constructor = TravelInsurancePolicyExtendView;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        TravelInsurancePolicyExtendView.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                {
                    name: 'travelInsurancePolicyExtend',
                    realName: 'travelInsurancePolicyExtend',
                    type: 'TravelInsurancePolicyExtend',
                },
                { name: 'travelInsurancePolicyExtendAges', realName: 'travelInsurancePolicyExtendAges', array: true },
                {
                    name: 'travelInsurancePolicyExtendPassengers',
                    realName: 'travelInsurancePolicyExtendPassengers',
                    array: true,
                }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        TravelInsurancePolicyExtendView.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {TravelInsurancePolicyExtend}
         */
        TravelInsurancePolicyExtendView.prototype.getTravelInsurancePolicyExtend = function () {
            return this.travelInsurancePolicyExtend;
        };
    
        /**
         * Setter for TravelInsurancePolicyExtend
         * 
         * @param {TravelInsurancePolicyExtend} value 
         */
        TravelInsurancePolicyExtendView.prototype.setTravelInsurancePolicyExtend = function (value) {
            this.travelInsurancePolicyExtend = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array}
         */
        TravelInsurancePolicyExtendView.prototype.getTravelInsurancePolicyExtendAges = function () {
            return this.travelInsurancePolicyExtendAges;
        };
    
        /**
         * Setter for TravelInsurancePolicyExtendAges
         * 
         * @param {array} value 
         */
        TravelInsurancePolicyExtendView.prototype.setTravelInsurancePolicyExtendAges = function (value) {
            this.travelInsurancePolicyExtendAges = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array}
         */
        TravelInsurancePolicyExtendView.prototype.getTravelInsurancePolicyExtendPassengers = function () {
            return this.travelInsurancePolicyExtendPassengers;
        };
    
        /**
         * Setter for TravelInsurancePolicyExtendPassengers
         * 
         * @param {array} value 
         */
        TravelInsurancePolicyExtendView.prototype.setTravelInsurancePolicyExtendPassengers = function (value) {
            this.travelInsurancePolicyExtendPassengers = value;
        };
    
        return TravelInsurancePolicyExtendView;
    }

}(angular));
